### PR TITLE
updates to mobile nav

### PR DESCRIPTION
**Pull request by CheetoMao**
connects to /whereyart/450

- added bootstrap markup to navigation
-  styles for these updates are over here: https://github.com/revelrylabs/whereyart/pull/459

### CODE REVIEW

**Comment by CheetoMao** [comment]
@pjdiiori I need some help figuring out those travis errors

**Comment by pjdiiori** [comment]
one of the errors is: `PHP 5.3 is supported only on Precise.` and from reading [these docs](https://docs.travis-ci.com/user/reference/trusty#php-images) which say...

> _Note: We do not support PHP versions 5.2.x and 5.3.x on Trusty. Specifying it will result in build failure. If you need to test with these versions, use Precise._

...so we may need to update the `travis.yml` to something like this?

```yml
language: php

php:
  - 5.4
  - 5.5

jobs:
  include:
    - php: 5.3
    dist: precise

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: phpunit

```
@grossvogel what do you think?

**Comment by pjdiiori** [comment]
and it looks like the other errors are throwing 404s when trying to download the `.tar` files for php 5.4 and 5.5?

**Comment by grossvogel** [comment]
Hmm... what I'd prefer to try is testing on the single PHP version we're actually running rather than three very old versions that _aren't_ what the app uses

**Review by pjdiiori — APPROVED** [review]
@CheetoMao you can go ahead and merge this. @grossvogel and I tried and failed to get the travis builds to pass. I created an issue to tackle it another time. merging this shouldn't break anything since it's just cosmetic changes.

**Pull request merged**
